spring:
  application:
    name: aiproxy-service

  main:
    allow-bean-definition-overriding: true

  webflux:
    stream:
      timeout: 300s

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:aiproxy}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:zj200101272531}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate # Use Flyway for schema management
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: ${JPA_SHOW_SQL:false}

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
        shutdown-timeout: 100ms

server:
  port: ${SERVER_PORT:8080}
  netty:
    connection-timeout: 10s
    idle-timeout: 60s

relay:
  admin:
    auto-create: true  # 自动创建管理员账号
    username: admin    # 管理员用户名
    password:          # 管理员密码（留空则自动生成）

  claude:
    base-url: ${CLAUDE_BASE_URL:https://api.anthropic.com}
    version: 2024-10-22
    models:
      - claude-opus-4-1-20250805      # Claude Opus 4.1 - 最新最强模型
      - claude-opus-4-20250514         # Claude Opus 4
      - claude-sonnet-4-20250514       # Claude Sonnet 4
      - claude-3-7-sonnet-20250219     # Claude Sonnet 3.7
      - claude-3-5-haiku-20241022      # Claude Haiku 3.5
      - claude-3-haiku-20240307        # Claude Haiku 3

  account-pool:
    max-retry-attempts: ${MAX_RETRY_ATTEMPTS:3}  # 最大重试次数，0=不重试，默认3次
    enable-retry: ${ENABLE_RETRY:true}  # 是否启用重试机制
    selection-strategy: ${SELECTION_STRATEGY:random}  # 账号选择策略: random, round-robin, least-used
    health-check-interval: ${HEALTH_CHECK_INTERVAL:30000}  # 健康检查间隔（毫秒）
    account-sync-interval: ${ACCOUNT_SYNC_INTERVAL:30000}  # OAuth账号同步间隔（毫秒）
    max-consecutive-failures: ${MAX_CONSECUTIVE_FAILURES:5}  # 连续失败多少次后禁用账号
    health-threshold: ${HEALTH_THRESHOLD:3}  # 连续失败多少次后标记为不健康

  gemini:
    base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
    api-key: ${GEMINI_API_KEY:}

  security:
    jwt:
      secret: ${JWT_SECRET:DefaultJWTSecretKey12345678901234567890}
      expiration: 86400000  # 24 hours
    encryption:
      key: ${ENCRYPTION_KEY:DefaultEncryptionKey123456789012}

  rate-limit:
    enabled: true
    default:
      requests-per-minute: 60
      requests-per-hour: 1000
      tokens-per-day: 1000000

  proxy:
    enabled: ${PROXY_ENABLED:false}
    type: ${PROXY_TYPE:socks5}
    host: ${PROXY_HOST:}
    port: ${PROXY_PORT:1080}
    username: ${PROXY_USERNAME:}
    password: ${PROXY_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}

logging:
  level:
    root: INFO
    com.aiproxy: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
