spring:
  application:
    name: aiproxy-service

  main:
    allow-bean-definition-overriding: true

  webflux:
    stream:
      timeout: 300s

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:aiproxy}?useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}  # 必须通过环境变量设置
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}  # 必须通过环境变量设置
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
        shutdown-timeout: 100ms

server:
  port: 8080  # 使用指定的端口
  netty:
    connection-timeout: 10s
    idle-timeout: 60s

relay:
  admin:
    auto-create: true
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:}  # 必须通过环境变量设置

  claude:
    base-url: https://api.anthropic.com
    version: 2024-10-22
    models:
      - claude-opus-4-1-20250805
      - claude-opus-4-20250514
      - claude-sonnet-4-20250514
      - claude-3-7-sonnet-20250219
      - claude-3-5-haiku-20241022
      - claude-3-haiku-20240307

  account-pool:
    max-retry-attempts: 3
    enable-retry: true
    selection-strategy: random
    health-check-interval: 30000
    account-sync-interval: 30000
    max-consecutive-failures: 5
    health-threshold: 3

  gemini:
    base-url: https://generativelanguage.googleapis.com
    api-key: # Gemini API密钥

  security:
    jwt:
      secret: ${JWT_SECRET:}  # 必须通过环境变量设置（至少32个字符）
      expiration: 86400000  # 24 hours
    encryption:
      key: ${ENCRYPTION_KEY:}  # 必须通过环境变量设置（必须32个字符）

  rate-limit:
    enabled: true
    default:
      requests-per-minute: 60
      requests-per-hour: 1000
      tokens-per-day: 1000000

  proxy:
    enabled: false
    type: socks5
    host:
    port: 1080
    username:
    password:

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: production

logging:
  level:
    root: INFO
    com.aiproxy: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    reactor.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/claude-relay/application.log
    max-size: 100MB
    max-history: 30
